version: 2.1

jobs:
  build-image:
    machine:
      image: ubuntu-2204:2022.04.1

    steps:
      - checkout
      - run:
          name: "Install Dependencies"
          command: |
            ./scripts/install_dependencies.sh
            sudo apt-get install tree
      - run:
          name: "Step 1"
          command: ./RootStock-NG.sh -c configs/bb.org-debian-bullseye-minimal-v5.10-ti-armhf.conf
      - run:
          name: "Step 2"
          command: |
            cd deploy/$(ls deploy | grep -v tar)
            sudo ./setup_sdcard.sh --img-4gb am335x-debian-11.2-iot-armhf-2022-01-01 \
              --dtb beaglebone --distro-bootloader --enable-cape-universal \
              --enable-uboot-disable-pru --enable-bypass-bootup-scripts

workflows:
  build-all:
    jobs:
      - build-image
